version = 3

[palette]
  bg = '#444444'
  cerror = '#D70000'
  csuccess = '#5FAF00'
  date = '#5F8787'
  git = '#5FD700'
  host = '#FF00FF'
  jobs = '#00AFAF'
  os = '#EEEEEE'
  path = '#00D7FF'
  pdefault = '#444444'
  perror = '#FF0000'
  psuccess = '#5FD700'
  rbg = '#444444'
  root = '#D7AF00'
  rseparator = '#949494'
  separator = '#949494'
  time = '#A8A8A8'
  user = '#D7AF87'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:pdefault'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'p:psuccess'
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}p:perror{{ end }}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .Icon }} <p:separator></>'
    foreground = 'p:os'
    background = 'p:bg'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if ne .Env.POSH_SESSION_DEFAULT_USER .UserName }}{{ if .Root }}<p:root><b>{{ .UserName }}</b></>{{ else }}<p:user>{{ .UserName }}</>{{ end }}<#7a7a7a>@</>{{ end }}{{ .HostName }} {{ if .SSHSession }} {{ end }}<p:separator></>'
    foreground = 'p:host'
    background = 'p:bg'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Writable }} {{ end }}{{ .Path }} '
    foreground = 'p:path'
    background = 'p:bg'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = ''
      folder_separator_icon = '  '
      home_icon = ''
      style = 'agnoster'

  [[blocks.segments]]
    template = '<p:separator> </>{{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }} '
    foreground = 'p:git'
    background = 'p:bg'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      commit_icon = '@'
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = ''
    foreground = 'p:bg'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = ''
    foreground = 'p:rbg'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if gt .Code 0 }}<b>{{ reason .Code }}</b> ✘{{ else }}{{ end }} <p:rseparator></>'
    foreground = 'p:csuccess'
    background = 'p:rbg'
    type = 'status'
    style = 'powerline'
    foreground_templates = ['{{ if gt .Code 0 }}p:cerror{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }}   <p:rseparator></>'
    foreground = 'p:time'
    background = 'p:rbg'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

  [[blocks.segments]]
    template = ' {{ if gt (int (.Env.BG_JOBS)) 0 }}{{ if gt (int (.Env.BG_JOBS)) 1 }}{{ .Env.BG_JOBS }} {{ end }} <p:rseparator></>{{ end }}'
    foreground = 'p:jobs'
    background = 'p:rbg'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = 'p:date'
    background = 'p:rbg'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = 'p:pdefault'
    background = 'transparent'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
