(require 'web-mode)
(add-to-list 'auto-mode-alist '("[.]p?html?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("[.]ctp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("[.]js\\'" . web-mode))
(add-to-list 'auto-mode-alist '("[.]j2\\'" . web-mode))
(add-to-list 'auto-mode-alist '("[.]php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("[.]hh\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("[.]zsh\\'" . sh-mode))
(setq web-mode-markup-indent-offset 2)
(setq web-mode-enable-auto-closing t)
(setq web-mode-enable-css-colorization t)
(provide 'setup-modes)
